Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,25 +1,44 @@
-name: .NET
+name: .NET CI/CD - Nuget Publish
 
 on:
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    branches: [master]
 
 jobs:
-  build:
-
+  build-and-publish:
     runs-on: ubuntu-latest
-
+    outputs:
+      version: ${{ steps.calc-version.outputs.version }}  # Define output for this job
     steps:
-    - uses: actions/checkout@v3
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v2
-      with:
-        dotnet-version: 6.0.x
-    - name: Restore dependencies
-      run: dotnet restore
-    - name: Build
-      run: dotnet build --no-restore
-    - name: Test
-      run: dotnet test --no-build --verbosity normal
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Calculate version
+        id: calc-version
+        run: echo "::set-output name=version::1.0.${{ github.run_number }}"
+
+      - name: Update version in csproj
+        run: |
+          sed -i 's|<Version>.*</Version>|<Version>${{ steps.calc-version.outputs.version }}</Version>|g' ./LoggingStandards/CerberusClientLogging.csproj
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 7.0.x
+
+      - name: Build
+        run: dotnet build --configuration Release
+
+      - name: Pack
+        run: dotnet pack --no-restore --verbosity normal --output ./nupkgs --configuration Release
+
+      - name: Push to NuGet
+        id: nuget-push
+        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
+
+      - name: Check NuGet Push Result
+        run: |
+          if [ ${{ steps.nuget-push.exit-code }} -ne 0 ]; then
+            echo "NuGet package push failed."
+            exit 1
+          fi
